### ISSUE TITLE
Firefox 106: Context Menu occationally disappear

### ISSUE THREAD

**Issue by yorkxin** [yorkxin/copy-as-markdown#109]
## Summary

Context menu is sometimes not showing up in Firefox 106. 

Not always reproducible.

Edit: seems to be related to non-persistent background page.

**Comment by manuzhang** [comment]
I'm seeing this issue now with Firefox 106.0.5. It always disappears.

**Comment by yorkxin** [comment]
@manuzhang thanks. I'm using Firefox too, but I can't tell under what situation it appears or disappears...

**Comment by manuzhang** [comment]
Disabling and re-enabling the extension gives me back one item in the context menu. However, there should be more?
<img width="342" alt="image" src="https://user-images.githubusercontent.com/1191767/202610842-bf9ce98d-55bd-4e80-828d-629581183fe1.png">

**Comment by yorkxin** [comment]
@manuzhang thanks. I guess I know where the issue comes from (related: https://github.com/yorkxin/copy-as-markdown/issues/107)

Regarding to the list of context menus, it depends on the item that you clicked. On a link it only shows Copy Link. On an image it shows Copy Image and Copy Image + Link command. On other places on the web page, it shows Copy Current Tab.

**Comment by manuzhang** [comment]
so is this already fixed in latest version?

**Comment by yorkxin** [comment]
No, I think the issue still exists after #107 🥲 In fact I don't see context menu on my Firefox today.

**Comment by yorkxin** [comment]
Dear folks, do you still experience this issue?

**Comment by manuzhang** [comment]
The issue still exists in  110.0.1 and I need to re-enable the extension to work around as well.

**Comment by yorkxin** [comment]
Hi all, I've released a new version 2.8.3, and hopefully this time the issue gets resolved. Please let me know how it goes!

**Comment by manuzhang** [comment]
@yorkxin Same for me on Firefox 113.0.1. Disabling and enabling the extension no longer works.

**Comment by azzamsa** [comment]
Compared to other extension. It always warn me about "Permission needed to read and change data"
Firefox indicate this with a blue dot.

![image](https://github.com/yorkxin/copy-as-markdown/assets/17734314/a9817019-859e-48e1-a930-ce664fb95794)

**Comment by azzamsa** [comment]
I tried `113.0.2` but the context menu is still missing. I don't know why other context menu are there.

![image](https://github.com/yorkxin/copy-as-markdown/assets/17734314/c02fe93e-1279-45d5-8d21-8af6b887cd63)

I have tried to use Brave because this extension works seamlessly in Brave. However, sometimes it needs a Google service extension. It is the reason I move back to Firefox.

I know it is an open-source project. It is not first-class paid ticket support. But I hope it will get resolved, as I use this extension a zillion times a day.

**Comment by azzamsa** [comment]
After couple of day. Maybe restart / other updates I did. Now I can use the context menu in `113.0.2` :tada: 

![image](https://github.com/yorkxin/copy-as-markdown/assets/17734314/3935d0c7-b845-49fe-ab97-90888fdf9779)

**Comment by Ganton** [comment]
It also happens to me using Firefox 113.0.2, even after restarting it, and disabling and enabling Copy as Markdown...

**Comment by manuzhang** [comment]
The issue no longer exists in Firefox 114.0.2

**Comment by redeyes2015** [comment]
For me, after re-installing the extension in Firefox 114.0.2, and clicking the extension icon in the menu bar, the item in context menu shows up properly.

**Comment by manuzhang** [comment]
This issue reappeared in 115.0.2 (64-bit)

**Comment by jhermann** [comment]
Works for me in FF 102 32bit ESR, and does **not** in FF 116 64bit, both under Windows 11.

**Comment by Ganton** [comment]
Does not works for me in FF 102 32bit ESR, and does not in FF 116 64bit, both under Windows 11.

> Works for me in FF 102 32bit ESR, and does **not** in FF 116 64bit, both under Windows 11.

Does not work for me in FF 116 64bit under Linux.

**Comment by hesselmonk** [comment]
Ironically this issue is fixed for me by downgrading the plugin to `Version 2.7.1` using `FireFox 119.0 (64-bit)` on Windows

**Comment by StefanBrand** [comment]
I downgraded to version 2.7.1 and context menu immediately started to appear again.

**Comment by yorkxin** [comment]
Memo: this is a known issue in Firefox MV3. https://discourse.mozilla.org/t/strange-mv3-behaviour-browser-runtime-oninstalled-event-and-menus-create/111208/14

Some extensions such as Leechblock NG, use a 1 second polling to recreate menus.

**Comment by yorkxin** [comment]
Hi all, I've introduced a new version 2.9.1 as an attempt to resolve this issue. If the issue still exists, I will try to reimplement some code for the Firefox version. (For developers: Specifically, changing the extension's architecture from MV3 to MV2)

Please upgrade to 2.9.1 and see if the issue still exist. Thanks!

**Comment by manuzhang** [comment]
2.8.3 is working for me on Firefox 124.0.2 (64-bit)

**Comment by yorkxin** [comment]
Has anyone encounter this issue recently (since May 2024)?

**Comment by manuzhang** [comment]
I haven't seen this issue since my comment above ☝️

**Comment by yorkxin** [comment]
Thanks! I'll close this for now.
